### ISSUE TITLE
Provider error in terraform plan

### ISSUE THREAD

**Issue by tomasn4a** [arindam0310018/12-Oct-2023-DevOps__Terraform-Deployment-Using-Workload-Identity-Federation#1]
Hello,

First of all thanks very much for the video and code explaining this thorny topic. I've been trying to replicate it in my setup and moving to workload identity federation but I'm getting an error when reaching the `terraform plan` step in my azure devops pipeline.

Even though I'm passing `ARM_USE_AZUREAD: true` to the step and setting the `environmentServiceNameAzureRM` input it complains that: 

```bash
│ Error: building AzureRM Client: obtain subscription(***) from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on providers.tf line 12, in provider "azurerm":
│   12: provider "azurerm" {
```

I've double checked that my service principal has contributor access to the subscription and the correct access permissions to the storage account which stores the states.

I've also made sure that my provider block looks just like yours:

```bash
provider "azurerm" {
  features {}
  skip_provider_registration = true
}
```

Any idea why it might be happening?

Many thanks!

**Comment by arindam0310018** [comment]
Hello Tomas, Thank you for reaching out! Please allow me sometime to validate in my end. I am at the moment in my vacation and will return tomorrow.Post that I will check and revert in details Thank youBest Regards, Arindam MitraSent from my iPhoneOn 28 Apr 2024, at 16:02, Tomas Rojo ***@***.***> wrote:﻿
Hello,
First of all thanks very much for the video and code explaining this thorny topic. I've been trying to replicate it in my setup and moving to workload identity federation but I'm getting an error when reaching the terraform plan step in my azure devops pipeline.
Even though I'm passing ARM_USE_AZUREAD: true to the step and setting the environmentServiceNameAzureRM input it complains that:
│ Error: building AzureRM Client: obtain subscription(***) from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on providers.tf line 12, in provider "azurerm":
│   12: provider "azurerm" {
I've double checked that my service principal has contributor access to the subscription and the correct access permissions to the storage account which stores the states.
I've also made sure that my provider block looks just like yours:
provider "azurerm" {
  features {}
  skip_provider_registration = true
}
Any idea why it might be happening?
Many thanks!

**Comment by tomasn4a** [comment]
Hi Arim, thanks for the quick response and sorry to bother you on your holidays.

I have solved the issue: I had been planning iterating on my terraform script locally on my machine (using CLI authentication) and I had commited and pushed the terraform lock file so it was still trying to use that authentication method. Removing the tf lock fixed the issue.

Thanks again!
